name       : freepats
version    : 1.0.2
release    : 2
source     :
    - https://github.com/feross/freepats/archive/v1.0.2.tar.gz : 6c76670d437382cc0c247469d11c72f312c0d15b5da6a65ae0f7fad4b60b96c2
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Old FreePats General MIDI sound set
description: |
    Old version of FreePats General MIDI sound set, initially put together by Eric A. Welsh more than 12 years ago.
install    : |-
    install -dm00644 $installdir/usr/share/soundfonts/freepats/Drum_000
    install -m00644 Drum_000/*.pat $installdir/usr/share/soundfonts/freepats/Drum_000/

    install -dm00644 $installdir/usr/share/soundfonts/freepats/Tone_000
    install -m00644 Tone_000/*.pat $installdir/usr/share/soundfonts/freepats/Tone_000/

    sed -i 's|Drum_000|/usr/share/soundfonts/freepats/Drum_000|g' freepats.cfg
    sed -i 's|Tone_000|/usr/share/soundfonts/freepats/Tone_000|g' freepats.cfg
    install -Dm00644 freepats.cfg $installdir/etc/timidity/freepats.cfg
